# Site settings
title: Open Source Design
email:
description: > # this means to ignore newlines until "baseurl:"
  We are a community of designers and developers aiming to push more
  open design processes and improve the user experience and interface
  design of open source software.

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opensourcedesign.net" # the base hostname & protocol for your site
exclude: ["bower_components", "node_modules", "grunt", "sass", "scripts", "bower.json", "package.json", "README.md"]

twitter_username: opensrcdesign
github_username:  opensourcedesign

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  organization:
    output: true
    permalink: /organization/:path/
  resources:
    output: true
    permalink: /resources/:path/
  people:
    output: true
    permalink: /people/:path/

sass:
    style: compressed

source_url: "https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/"
edit_url: "https://edit.opensourcedesign.net/#opensourcedesign/opensourcedesign.github.io/edit/master/"

# Prose Config - what is seen at https://edit.opensourcedesign.net
# Docs: https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl:
  ignore:
    - '_includes'
    - '_layouts'
    - '_sass'
    - 'css'
    - 'fonts'
    - 'images'
    - 'js'
    - 'scripts'
    - '.gitignore'
    - '.travis.yml'
    - '_config-dev.yml'
    - '_config.yml'
    - 'CNAME'
    - 'feed.xml'
    - 'Gemfile'
    - 'index.html'
    - 'LICENSE'
    - 'Rakefile'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
          placeholder: "Categories"
          value: ""
    _posts/jobs:
      - name: "_id"
        field:
          element: "hidden"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "jobs"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "organization"
        field:
          element: "text"
          label: "Organization"
          value: ""
      - name: "org_url"
        field:
          element: "text"
          label: "Organization URL"
          value: ""
      - name: "status"
        field:
          element: "select"
          label: "Job Status"
          placeholder: "Job Status"
          options: *status
          selected: ""
      - name: "role"
        field:
          element: "multiselect"
          label: "Roles"
          placeholder: "Roles"
          options: *roles
          selected: ""
      - name: "compensation"
        field:
          element: "select"
          label: "Compensation"
          placeholder: "Compensation"
          options: *compensation
          selected: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Tags"
          value: ""
    _posts/events:
      - name: "layout"
        field:
          element: "hidden"
          value: "event"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "status"
        field:
          element: "select"
          label: "Event Status"
          placeholder: "Event Status"
          options: *status
          selected: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Tags"
          value: ""
    _pages:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          placeholder: "Layout"
          options:
            - name: "Default"
              value: "default"
            - name: "Page"
              value: "page"
            - name: "Post"
              value: "post"
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
          placeholder: "Categories"
          value: ""
